version: '2.2'
services:  
    
    kafka:
        image: spotify/kafka
        scale: 1
        ports:
            - 2181:2181
            - 9092:9092
        environment:
            - ADVERTISED_PORT=9092
            - ADVERTISED_HOST=localhost

    jenkins:
        image: jenkins
        ports:
            - 8181:8181
            - 5010:5010

    mongo:
        image: mongo
        ports:
            - 27017:27017

    solr:
        image: solr
        ports:
            - 8983:8983
        volumes:
            - data:/opt/solr/server/solr/mycores
        entrypoint:
            - docker-entrypoint.sh
            - solr-precreate
            - mycore

volumes:
    data: